# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_home_email', models.CharField(max_length=100)),
                ('contact_home_phone', models.CharField(max_length=100)),
                ('contact_work_email', models.CharField(max_length=100)),
                ('contact_work_phone', models.CharField(max_length=100)),
                ('credit_address', models.CharField(max_length=100)),
                ('msisdn', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('ssn', models.CharField(max_length=11)),
            ],
        ),
    ]
